version: '3.5'

volumes:
  mongodb-volume:

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27888:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    volumes:
      - mongodb-volume:/data/db